services:
  ubuntu_gate_app:
    image: ghcr.io/amacado/ubuntu-gate/ubuntu-gate:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.ubuntu-gate.rule=Host(`ubuntu-gate.de`) || Host(`www.ubuntu-gate.de`)
      - traefik.http.routers.ubuntu-gate.entrypoints=websecure
      - traefik.http.routers.ubuntu-gate.tls.certresolver=le
      - traefik.http.services.ubuntu-gate.loadbalancer.server.port=8080
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
